name: Build and Test

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    # pull and build wolfssl
    - name: Checkout wolfssl
      uses: actions/checkout@master
      with:
        repository: wolfssl/wolfssl
        path: wolfssl

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config build-essential

    # Build wolfSSL with required features
    - name: Build wolfssl
      run: |
        cd wolfssl
        ./autogen.sh
        ./configure --enable-debug --enable-shared --enable-cryptocb --enable-aescfb --enable-keygen --enable-certgen --enable-certreq --enable-certext --enable-pkcs7 --enable-rng --enable-harden --enable-static
        make
        sudo make install
        sudo ldconfig
        cd ..

    # pull and build wolfhsm
    - name: Checkout wolfhsm
      uses: actions/checkout@master
      with:
        repository: wolfssl/wolfhsm
        path: wolfhsm

    # Build wolfHSM with examples enabled
    - name: Build wolfhsm
      run: |
        cd wolfhsm
        ./autogen.sh
        ./configure --with-wolfssl=/usr/local --enable-debug --enable-examples
        make
        sudo make install
        sudo ldconfig
        cd ..

    # Build and test POSIX examples
    - name: Build and test POSIX examples
      run: |
        ls && cd posix/tcp/wh_server_tcp && make WOLFSSL_DIR=../../../wolfssl WOLFHSM_DIR=../../../wolfhsm
        cd ../wh_client_tcp && make WOLFSSL_DIR=../../../wolfssl WOLFHSM_DIR=../../../wolfhsm
        cd ../wh_server_tcp && ./Build/wh_server_tcp.elf &
        SERVER_PID=$!
        echo "TCP_SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
        cd ../wh_client_tcp && ./Build/wh_client_tcp.elf
        kill $SERVER_PID || true


