name: Build and Test

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    # pull and build wolfssl
    - name: Checkout wolfssl
      uses: actions/checkout@master
      with:
        repository: wolfssl/wolfssl
        path: wolfssl

    # pull and build wolhsm
    - name: Checkout wolfhsm
      uses: actions/checkout@master
      with:
        repository: wolfssl/wolfhsm
        path: wolfhsm

    # Run POSIX demo (builds and tests server/client)
    - name: Run POSIX demo
      run: |
        chmod +x ./run_posix_demo.sh
        export WOLFSSL_DIR=${{ github.workspace }}/wolfssl
        export WOLFHSM_DIR=${{ github.workspace }}/wolfhsm
        ./run_posix_demo.sh


