name: Build and Test

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    # pull and build wolfssl
    - name: Checkout wolfssl
      uses: actions/checkout@master
      with:
        repository: wolfssl/wolfssl
        path: wolfssl

    # pull and build wolfhsm
    - name: Checkout wolfhsm
      uses: actions/checkout@master
      with:
        repository: wolfssl/wolfhsm
        path: wolfhsm

    # Build examples
    - name: Build POSIX TCP server
      run: |
        cd posix/tcp/wh_server_tcp
        make WOLFSSL_DIR=../../../wolfssl WOLFHSM_DIR=../../../wolfhsm/test/Build
    - name: Build POSIX TCP client
      run: |
        cd posix/tcp/wh_client_tcp
        make WOLFSSL_DIR=../../../wolfssl WOLFHSM_DIR=../../../wolfhsm/test/Build

    # Install build dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool

    # Build wolfSSL
    - name: Build wolfSSL
      run: |
        cd wolfssl
        ./autogen.sh
        ./configure --enable-shared --enable-debug --prefix=/usr
        make -j$(nproc)
        sudo make install
        sudo ldconfig
        cd ..

    # Build wolfHSM
    - name: Build wolfHSM
      run: |
        cd wolfhsm
        # Build test which includes all components
        cd test
        mkdir -p Build
        make -j$(nproc) WOLFSSL_DIR=/usr DEBUG=1
        cd ../..

    # Run server and client tests
    - name: Run POSIX TCP tests
      run: |
        chmod +x scripts/run_posix_demo.sh
        pwd
        ls -la
        ls -la posix/tcp/wh_server_tcp/Build/
        ls -la posix/tcp/wh_client_tcp/Build/
        chmod +x posix/tcp/wh_server_tcp/Build/wh_server_tcp.elf
        chmod +x posix/tcp/wh_client_tcp/Build/wh_client_tcp.elf
        # Run the demo with debug output
        WOLFSSL_DIR=$PWD/wolfssl WOLFHSM_DIR=$PWD/wolfhsm TERM=xterm-256color ./scripts/run_posix_demo.sh


