name: Build and Test

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    # pull and build wolfssl
    - name: Checkout wolfssl
      uses: actions/checkout@master
      with:
        repository: wolfssl/wolfssl
        path: wolfssl

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config build-essential

    - name: Build wolfssl
      run: |
        cd wolfssl
        ./autogen.sh
        CFLAGS="-DWOLFSSL_DEBUG" ./configure --enable-keygen --enable-certgen --enable-certreq --enable-certext --enable-pkcs7 --enable-cryptocb --enable-aescfb --enable-debug --enable-harden
        make
        sudo make install
        sudo ldconfig
        cd ..

    # pull and build wolfhsm
    - name: Checkout wolfhsm
      uses: actions/checkout@master
      with:
        repository: wolfssl/wolfhsm
        path: wolfhsm

    - name: Build wolfhsm
      run: |
        cd wolfhsm
        ./autogen.sh
        PKG_CONFIG_PATH=${{ github.workspace }}/wolfssl/lib/pkgconfig ./configure --with-wolfssl=${{ github.workspace }}/wolfssl --enable-debug --enable-examples
        make
        sudo make install
        sudo ldconfig
        cd ..

    # Run POSIX demo (builds and tests server/client)
    - name: Run POSIX demo
      run: |
        chmod +x ./run_posix_demo.sh
        export WOLFSSL_DIR=${{ github.workspace }}/wolfssl
        export WOLFHSM_DIR=${{ github.workspace }}/wolfhsm
        ./run_posix_demo.sh


