name: Build and Test

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    # pull and build wolfssl
    - name: Checkout wolfssl
      uses: actions/checkout@master
      with:
        repository: wolfssl/wolfssl
        path: wolfssl

    # pull and build wolfhsm
    - name: Checkout wolfhsm
      uses: actions/checkout@master
      with:
        repository: wolfssl/wolfhsm
        path: wolfhsm

    # Build examples
    - name: Build POSIX TCP server
      run: ls && cd posix/tcp/wh_server_tcp && make WOLFSSL_DIR=../../../wolfssl WOLFHSM_DIR=../../../wolfhsm
    - name: Build POSIX TCP client
      run: cd posix/tcp/wh_client_tcp && make WOLFSSL_DIR=../../../wolfssl WOLFHSM_DIR=../../../wolfhsm

    # Run server and client tests
    - name: Run POSIX TCP tests
      run: |
        chmod +x scripts/run_posix_demo.sh
        pwd
        ls -la
        ls -la posix/tcp/wh_server_tcp/Build/
        ls -la posix/tcp/wh_client_tcp/Build/
        chmod +x posix/tcp/wh_server_tcp/Build/wh_server_tcp.elf
        chmod +x posix/tcp/wh_client_tcp/Build/wh_client_tcp.elf
        # Configure and build wolfSSL
        cd wolfssl
        ./configure --enable-shared
        make -j$(nproc)
        cd ..
        # Configure and build wolfHSM
        cd wolfhsm
        ./configure --enable-shared WOLFSSL_DIR=$PWD/../wolfssl
        make -j$(nproc)
        cd ..
        # Run the demo
        WOLFSSL_DIR=$PWD/wolfssl WOLFHSM_DIR=$PWD/wolfhsm TERM=xterm-256color ./scripts/run_posix_demo.sh


